# Generated by Django 4.2.7 on 2023-12-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-date_create',), 'verbose_name': 'публикация', 'verbose_name_plural': 'публикации'},
        ),
    ]
