# Generated by Django 4.2.7 on 2023-12-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_version_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='активная версия'),
        ),
    ]
